# Generated by Django 3.1.3 on 2020-11-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainIndex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='matchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchname', models.CharField(max_length=20)),
                ('createuser', models.CharField(max_length=20)),
                ('matchtype', models.CharField(max_length=4)),
            ],
        ),
    ]
