# Generated by Django 3.1.3 on 2020-11-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainIndex', '0002_matchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gametype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gametype', models.CharField(max_length=20)),
            ],
        ),
    ]
