# Generated by Django 3.1.3 on 2020-12-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainIndex', '0008_fenzu_zhixuce'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhixuce',
            name='changci',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
