# Generated by Django 3.1.3 on 2020-12-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainIndex', '0009_zhixuce_changci'),
    ]

    operations = [
        migrations.CreateModel(
            name='saichang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zhixuceid', models.IntegerField()),
                ('huosheng', models.CharField(max_length=20)),
                ('fenshu1', models.IntegerField()),
                ('fenshu2', models.IntegerField()),
                ('huobai', models.CharField(max_length=20)),
            ],
        ),
    ]
