# Generated by Django 3.1.3 on 2020-12-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainIndex', '0010_saichang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zhixuce',
            name='matchdetail',
        ),
        migrations.AddField(
            model_name='zhixuce',
            name='player1',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zhixuce',
            name='player2',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
