# Generated by Django 3.1.3 on 2020-12-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainIndex', '0011_auto_20201217_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhixuce',
            name='huosheng',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
