# Generated by Django 3.1.3 on 2020-12-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainIndex', '0012_zhixuce_huosheng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zhixuce',
            name='huosheng',
        ),
    ]
