# Generated by Django 3.1.3 on 2020-12-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainIndex', '0013_remove_zhixuce_huosheng'),
    ]

    operations = [
        migrations.CreateModel(
            name='caipanall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchid', models.IntegerField()),
                ('caipan', models.CharField(max_length=200)),
            ],
        ),
    ]
